title: Histeregue Podcast
description: > 
  O podcast preferido do Capitão América.
baseurl: ""
url: "http://histeregue.com.br"

twitter_username: jekyllrb
github_username:  Histeregue

markdown: kramdown

sass:
  style: compressed

gems:
  - jekyll-coffeescript
  - jekyll-paginate

paginate: 10
paginate_path: /blog/:num/


