title: Histeregue Podcast
description: > 
  O podcast preferido do Capitão América.
baseurl: ""
url: "http://histeregue.com.br"

fonts: 
  - Quicksand # $base-font-size
  - Righteous # $title-font-size
  - Saira # ui-font-size

twitter_username: histeregue
github_username:  Histeregue

markdown: kramdown

sass:
  style: compressed

gems:
  - jekyll-coffeescript
  - jekyll-paginate

paginate: 10
paginate_path: /blog/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

